# Theme metadata
name = "my_theme"

# Is theme light or dark?
dark = true

# Primary
primary = "#004225"

# Menu
menu_primary = "#004225"
menu_text = "#fff"
menu_text_active = "#42001D"
menu_title = "#fff"

# Home sections
home_section_odd = "rgb(255, 255, 255)"
home_section_even = "rgb(247, 247, 247)"

